### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by rkistaps** [nehlis/iproject-iconcepts#1]
Why controllers are inserting data in to db?

**Comment by niels-bosman** [comment]
Hi @rkistaps. This is becuase the sole task of controllers is to fulfill these CRUD actions. And these CRUD actions do require database insertions. https://fuelphp.com/docs/general/controllers/base.html#:~:text=Controllers%20are%20classes%20that%20can,to%20a%20view%20for%20output.
